djangoProject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('',include('learning_logs.urls')),
]

learning_logs/urls.py
"""定义learning_logs的URL模式"""
from django.urls import path
from . import views  #从url所在目录导入views
app_name = 'learning_logs'
urlpatterns = [
    #主页
    #将url映射视图 匹配到url返回一个视图
    path('',views.index,name='index'),
    #显示所有的主题
    path('topics/',views.topics,name='topics'),
    #显示主题的详细信息
    path('topics/<int:topic_id>/',views.topic,name='topic'),
    #添加新的主题页面
    path('new_topic/',views.new_topic,name='new_topic'),
    #添加新的条目页
    path('new_entry/<int:topic_id>',views.new_entry,name='new_entry'),
    #编辑已有条目页面
    path('edit_entry/<int:entry_id>',views.edit_entry,name='edit_entry'),
]

users/urls.py
#为应用程序users定义url模式
from django.urls import path,include
from . import views
app_name = 'users'
urlpatterns = [
    #包含默认的身份验证url
    path('',include('django.contrib.auth.urls')),
    #注册页面
    path('register/',views.register,name='register')
]

learning_logs/models.py
from django.db import models
#将主题关联到特定用户
from django.contrib.auth.models import User
# Create your models here.
#这里创建模型，用于如何处理应用程序中存储的数据
class Topic(models.Model):
    """用户学习主题"""
    # 设置又字符串组成的数据作为文本 ， 长度为200个字节
    text = models.CharField(max_length=200)
    #记录日期True表示自动设置为当前日期和时间
    date_added = models.DateTimeField(auto_now_add=True)
    #建立到模型User的外键，用户删除，所相关联的主题也删除
    owner = models.ForeignKey(User,on_delete=models.CASCADE)
    def __str__(self):
        # 返回字符串表示
        return self.text

#添加条目，每个条目与特定的主题相关联，多对一关系， 多个条目可以关联到多个主题
class Entry(models.Model):
    # 某个主题的具体知识
    #外键关联到另一个主题， on_delte 在删除时删除相关条目
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    text = models.TextField() #长度不受限制
    date_added = models.DateTimeField(auto_now_add=True)

    # 存储管理模型的额外信息
    class Meta:
        verbose_name_plural = 'entries'
    def __str__(self):
        "返回模型字符串"
        return f"{self.text[:50]}..."

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms   #创建表单
from .models import Topic,Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text':''}

# 添加新的条目
class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':' '}
        widgets = {'text':forms.Textarea(attrs={'cols':80})}

learning_logs/views.py
from django.shortcuts import render,redirect
from .models import Topic ,Entry # 导入模板
from .forms import TopicForm,EntryForm
#作为装饰器，用户运行topics代码时候会检查是否登录，没有登录会返回登录页面
from django.contrib.auth.decorators import  login_required
from django.http import Http404 #没有请求资源返回404
# Create your views here.
def index(request):
    """学习笔记主页"""
    return render(request,'learning_logs/index.html')
@login_required
def topics(request):
    #显示所有主题
   # topics = Topic.objects.order_by('date_added')
    #hi只允许用户访问自己的主题，从数据库中获取owner属性 ，
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request,'learning_logs/topics.html',context)

def topic(request,topic_id):
    #显示主题的详细内容
    topic = Topic.objects.get(id=topic_id)
    #确认请求的主题属于当前用户, 如果请求的主题不贵用户，就会引发404
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic':topic,'entries':entries}
    return render(request,'learning_logs/topic.html',context)

def new_topic(request):
    #对提交的表单数据进行处理，并将用户重定向到页面topics
    """添加新主题"""
    if request.method != 'POST':
        #当请求是get请求发返回一个空的表单
        form = TopicForm()
    else:
        #post请求对提交数进行处理
        form = TopicForm(data=request.POST)
        # 如果表单有值，is_valid 方法会对表单进行检查
        if form.is_valid():
            #将新加的主题给定owner
            new_topic = form.save(commit=False)
            new_topic.owner = request.user # 将主题owner设为当前用户
            new_topic.save()
            return redirect('learning_logs:topics')  # 最后返回到topics视图
    context = {'form':form}
    return  render(request,'learning_logs/new_topic.html',context)

def new_entry(request,topic_id):
    #在特定主题中添加条目
    topic = Topic.objects.get(id = topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic',topic_id=topic_id)

    context = {'topic':topic,'form':form}
    return render(request,'learning_logs/new_entry.html',context)

def edit_entry(request,entry_id):
    #修改已有条目
    entry = Entry.objects.get(id=entry_id) # 获取已有条目
    topic = entry.topic # 条目关联的主题
    if request.method != 'POST':
        form = EntryForm(instance=entry) # 初始显示之前的条目信息
    else:
        form = EntryForm(instance=entry,data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic',topic_id=topic.id)
    context = {'entry':entry,'topic':topic,'form':form}
    return render(request,'learning_logs/edit_entry.html',context)

users/views.py
from django.shortcuts import render,redirect
#login函数以便用户注册后让其自动登录
from django.contrib.auth import login

from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):
    #注册新用户
    if request.method != 'POST':
        #显示空的注册表
        form = UserCreationForm()
    else:
        #处理填好的注册表单
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            #让新用户自动登录
            login(request,new_user)
            return redirect('learning_logs:index') # 登录后返回主页
    context= {'form':form}
    return render(request,'registration/register.html',context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
    <title>Title</title>
    <! --bootstrap自定义模板标签 -->
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>
<! --父模板-创建主页连接，在项目中每个页面都继承故模板，每个页面都有主页连接 -->

<nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <a class="navbar-brand" href="{% url 'learning_logs:index' %}">learning log</a>

    <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'learning_logs:topics' %}">Topics</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <span class="navbar-text">hello, {{ user.username }}</span>
                </li>
               <li class="nav-item">
                    <! -- 注销连接-- >
                    <a class="nav-link" href="{% url 'users:logout' %}">log out</a>
               </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">log in</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
<main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
        <! -- 占位符信息有子模版填充 -->
        {% block page_header %}{% endblock page_header %}
    </div>
    <div>
        <! -- 占位符信息有子模版填充 -->
        {% block content %}{% endblock content %}
    </div>
</main>

</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "learning_logs/base.html" %}
{% block content %}
<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
<p>edit entry:</p>
<form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
{% csrf_token %}
{{ form.as_p }}
<button name="submit">save chenges</button>
</form>
{% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>learning log</title>
</head>
<body>
<!-- 继承的模板 -->
{% extends "learning_logs/base.html" %}
{% block page_header %}
    <div class="jumbotron">
        <h1 class="display-3">Track your learning.</h1>
        <p class="lead">Make your own Learning Log,and keep a list of the topics you are learning about.
            Whenever you learn something new about a topic, make an entry summarizing what you are learned.</p>
        <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">Register &raquo;</a>
    </div>
{% endblock page_header %}
<!-- {% block content %}
<p>Learning Log</p>
<p>Learning log helps you keep track of your learning,for any topic you re learning about.</p>
{% endblock content %} 暂时不定义content -->
</body>
</html>

learning_logs/templates/learning_logs/new_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "learning_logs/base.html" %}
{% block content %}
<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
<p>Add a new entry:</p>
<form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>add entry</button>
</form>
{% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/new_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'learning_logs/base.html' %}
{% block content %}
<p>Add a new topic:</p>

<form action="{% url 'learning_logs:new_topic' %}" method="post">
    <! -- 防止攻击者利用表单获取对服务器未经授权的访问-->
    {% csrf_token %}
    <! --让表单自动显示所需的全部字段 -->
    {{ form.as_p }}
    <button name="submit">Add topic</button>

</form>
{% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>topic</title>
</head>
<body>
{% extends 'learning_logs/base.html' %}
{% block page_header %}
    <h3>{{ topic }}</h3>
{% endblock page_header %}
{% block content %}
<p>Topic: {{ topic }}</p>
    <p>Entries:</p>
    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
    </p>
{% for entry in entries %}
    <div class="card mb-3">
        <h4 class="card-header">
            {{ entry.date_added|date:'M d,Y H:i' }}
            <small> <a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a></small>
        </h4>
        <div class="card-body">
            {{ entry.text|linebreaks }}
        </div>
    </div>
    {% empty %}
        <p> There are no entries for this topic yet.</p>
    {% endfor %}

{% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/topics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "learning_logs/base.html" %}
{% block page_header %}
    <h1>Topics</h1>
{% endblock page_header %}
{% block content %}
<p>Topics</p>
    <ul>
        {% for topic in topics %}
             <li><h3>
                <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
             </h3></li>
        {% empty %}
            <li><h3>No topics have been added yet.</h3></li>
        {% endfor %}
    </ul>
    <h3><a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a></h3>
{% endblock content %}

</body>
</html>